

OrdererOrgs:

  - Name: Orderer
    Domain: example.com
    CA:
        Country: ES
        Province: Madrid
        Locality: Madrid
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
    

PeerOrgs:
  - Name: ecoFarm
    Domain: ecoFarm.example.com
    EnableNodeOUs: true
    CA:
      Country: ES
      Province: Madrid
      Locality: Madrid
    Template:
      Count: 1
    Users:
      Count: 1
 
  - Name: logisticTrans
    Domain: logisticTrans.example.com
    EnableNodeOUs: true
    CA:
        Country: ES
        Province: Madrid
        Locality: Madrid
    Template:
      Count: 1
    Users:
      Count: 1
  
   
  - Name: ecoMarket
    Domain: ecoMarket.example.com
    EnableNodeOUs: true
    CA:
        Country: ES
        Province: Madrid
        Locality: Madrid
    Template:
      Count: 1
    Users:
      Count: 1
  
    